// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wanderer.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_wanderer_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_wanderer_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_wanderer_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_wanderer_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_wanderer_2eproto;
namespace wanderer {
class S2G_RegisterInnerSession;
class S2G_RegisterInnerSessionDefaultTypeInternal;
extern S2G_RegisterInnerSessionDefaultTypeInternal _S2G_RegisterInnerSession_default_instance_;
}  // namespace wanderer
PROTOBUF_NAMESPACE_OPEN
template<> ::wanderer::S2G_RegisterInnerSession* Arena::CreateMaybeMessage<::wanderer::S2G_RegisterInnerSession>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace wanderer {

// ===================================================================

class S2G_RegisterInnerSession :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:wanderer.S2G_RegisterInnerSession) */ {
 public:
  S2G_RegisterInnerSession();
  virtual ~S2G_RegisterInnerSession();

  S2G_RegisterInnerSession(const S2G_RegisterInnerSession& from);
  S2G_RegisterInnerSession(S2G_RegisterInnerSession&& from) noexcept
    : S2G_RegisterInnerSession() {
    *this = ::std::move(from);
  }

  inline S2G_RegisterInnerSession& operator=(const S2G_RegisterInnerSession& from) {
    CopyFrom(from);
    return *this;
  }
  inline S2G_RegisterInnerSession& operator=(S2G_RegisterInnerSession&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const S2G_RegisterInnerSession& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const S2G_RegisterInnerSession* internal_default_instance() {
    return reinterpret_cast<const S2G_RegisterInnerSession*>(
               &_S2G_RegisterInnerSession_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(S2G_RegisterInnerSession& a, S2G_RegisterInnerSession& b) {
    a.Swap(&b);
  }
  inline void Swap(S2G_RegisterInnerSession* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S2G_RegisterInnerSession* New() const final {
    return CreateMaybeMessage<S2G_RegisterInnerSession>(nullptr);
  }

  S2G_RegisterInnerSession* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S2G_RegisterInnerSession>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S2G_RegisterInnerSession& from);
  void MergeFrom(const S2G_RegisterInnerSession& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S2G_RegisterInnerSession* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "wanderer.S2G_RegisterInnerSession";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_wanderer_2eproto);
    return ::descriptor_table_wanderer_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kSecretFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string secret = 2;
  void clear_secret();
  const std::string& secret() const;
  void set_secret(const std::string& value);
  void set_secret(std::string&& value);
  void set_secret(const char* value);
  void set_secret(const char* value, size_t size);
  std::string* mutable_secret();
  std::string* release_secret();
  void set_allocated_secret(std::string* secret);
  private:
  const std::string& _internal_secret() const;
  void _internal_set_secret(const std::string& value);
  std::string* _internal_mutable_secret();
  public:

  // @@protoc_insertion_point(class_scope:wanderer.S2G_RegisterInnerSession)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr secret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_wanderer_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// S2G_RegisterInnerSession

// string name = 1;
inline void S2G_RegisterInnerSession::clear_name() {
  name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& S2G_RegisterInnerSession::name() const {
  // @@protoc_insertion_point(field_get:wanderer.S2G_RegisterInnerSession.name)
  return _internal_name();
}
inline void S2G_RegisterInnerSession::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:wanderer.S2G_RegisterInnerSession.name)
}
inline std::string* S2G_RegisterInnerSession::mutable_name() {
  // @@protoc_insertion_point(field_mutable:wanderer.S2G_RegisterInnerSession.name)
  return _internal_mutable_name();
}
inline const std::string& S2G_RegisterInnerSession::_internal_name() const {
  return name_.GetNoArena();
}
inline void S2G_RegisterInnerSession::_internal_set_name(const std::string& value) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void S2G_RegisterInnerSession::set_name(std::string&& value) {
  
  name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wanderer.S2G_RegisterInnerSession.name)
}
inline void S2G_RegisterInnerSession::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wanderer.S2G_RegisterInnerSession.name)
}
inline void S2G_RegisterInnerSession::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wanderer.S2G_RegisterInnerSession.name)
}
inline std::string* S2G_RegisterInnerSession::_internal_mutable_name() {
  
  return name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* S2G_RegisterInnerSession::release_name() {
  // @@protoc_insertion_point(field_release:wanderer.S2G_RegisterInnerSession.name)
  
  return name_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void S2G_RegisterInnerSession::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:wanderer.S2G_RegisterInnerSession.name)
}

// string secret = 2;
inline void S2G_RegisterInnerSession::clear_secret() {
  secret_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& S2G_RegisterInnerSession::secret() const {
  // @@protoc_insertion_point(field_get:wanderer.S2G_RegisterInnerSession.secret)
  return _internal_secret();
}
inline void S2G_RegisterInnerSession::set_secret(const std::string& value) {
  _internal_set_secret(value);
  // @@protoc_insertion_point(field_set:wanderer.S2G_RegisterInnerSession.secret)
}
inline std::string* S2G_RegisterInnerSession::mutable_secret() {
  // @@protoc_insertion_point(field_mutable:wanderer.S2G_RegisterInnerSession.secret)
  return _internal_mutable_secret();
}
inline const std::string& S2G_RegisterInnerSession::_internal_secret() const {
  return secret_.GetNoArena();
}
inline void S2G_RegisterInnerSession::_internal_set_secret(const std::string& value) {
  
  secret_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void S2G_RegisterInnerSession::set_secret(std::string&& value) {
  
  secret_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:wanderer.S2G_RegisterInnerSession.secret)
}
inline void S2G_RegisterInnerSession::set_secret(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  secret_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:wanderer.S2G_RegisterInnerSession.secret)
}
inline void S2G_RegisterInnerSession::set_secret(const char* value, size_t size) {
  
  secret_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:wanderer.S2G_RegisterInnerSession.secret)
}
inline std::string* S2G_RegisterInnerSession::_internal_mutable_secret() {
  
  return secret_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* S2G_RegisterInnerSession::release_secret() {
  // @@protoc_insertion_point(field_release:wanderer.S2G_RegisterInnerSession.secret)
  
  return secret_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void S2G_RegisterInnerSession::set_allocated_secret(std::string* secret) {
  if (secret != nullptr) {
    
  } else {
    
  }
  secret_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), secret);
  // @@protoc_insertion_point(field_set_allocated:wanderer.S2G_RegisterInnerSession.secret)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace wanderer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_wanderer_2eproto
