# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wanderer.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='wanderer.proto',
  package='wanderer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ewanderer.proto\x12\x08wanderer\"8\n\x18S2G_RegisterInnerSession\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06secret\x18\x02 \x01(\tb\x06proto3'
)




_S2G_REGISTERINNERSESSION = _descriptor.Descriptor(
  name='S2G_RegisterInnerSession',
  full_name='wanderer.S2G_RegisterInnerSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='wanderer.S2G_RegisterInnerSession.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='secret', full_name='wanderer.S2G_RegisterInnerSession.secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['S2G_RegisterInnerSession'] = _S2G_REGISTERINNERSESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

S2G_RegisterInnerSession = _reflection.GeneratedProtocolMessageType('S2G_RegisterInnerSession', (_message.Message,), {
  'DESCRIPTOR' : _S2G_REGISTERINNERSESSION,
  '__module__' : 'wanderer_pb2'
  # @@protoc_insertion_point(class_scope:wanderer.S2G_RegisterInnerSession)
  })
_sym_db.RegisterMessage(S2G_RegisterInnerSession)


# @@protoc_insertion_point(module_scope)
