name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run build-test script
      run: |
       # pip3 install protobuf
        mkdir build && cd build
        cmake --no-warn-unused-cli -DCMAKE_TOOLCHAIN_FILE=../cmake/linux_clang.cmake ../ && make
        ./wanderer &
       # python3 ../client-test/client.py &
    

  
