name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run build-test script
      run: |
        apt install -y python3-protobuf
        mkdir build && cd build
        cmake ../ && make
        ./wanderer &
        python3 ../client-test/client.py &
    

  
